"""fix_tables

Revision ID: 529895692ee9
Revises: add_dynamic_interviewers_table
Create Date: 2026-10-01 10:57:03.861128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '529895692ee9'
down_revision: Union[str, None] = 'add_dynamic_interviewers_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_refresh_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_resume_processing_jobs_created_at'), table_name='resume_processing_jobs')
    op.drop_index(op.f('ix_resume_processing_jobs_session_id'), table_name='resume_processing_jobs')
    op.drop_index(op.f('ix_resume_processing_jobs_status'), table_name='resume_processing_jobs')
    op.drop_index(op.f('ix_resume_processing_jobs_user_id'), table_name='resume_processing_jobs')
    op.drop_table('resume_processing_jobs')

    op.drop_index(op.f('idx_approved_pool_approved'), table_name='approved_question_pools')
    op.drop_index(op.f('idx_approved_pool_session'), table_name='approved_question_pools')
    op.create_index(op.f('ix_approved_question_pools_admin_approved'), 'approved_question_pools', ['admin_approved'], unique=False)
    op.create_index(op.f('ix_approved_question_pools_id'), 'approved_question_pools', ['id'], unique=False)
    op.create_index(op.f('ix_approved_question_pools_session_id'), 'approved_question_pools', ['session_id'], unique=False)
    op.alter_column('aptitude_attempts', 'selected_option',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.drop_constraint(op.f('aptitude_attempts_round_id_attempt_number_key'), 'aptitude_attempts', type_='unique')
    op.create_index(op.f('ix_aptitude_attempts_id'), 'aptitude_attempts', ['id'], unique=False)
    op.alter_column('aptitude_questions', 'correct_option',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_index(op.f('idx_aptitude_difficulty'), table_name='aptitude_questions')
    op.create_index(op.f('ix_aptitude_questions_difficulty'), 'aptitude_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_aptitude_questions_id'), 'aptitude_questions', ['id'], unique=False)
    op.create_index(op.f('ix_aptitude_topics_id'), 'aptitude_topics', ['id'], unique=False)
    op.alter_column('assessment_rounds', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('assessment_rounds', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_round_session'), table_name='assessment_rounds')
    op.drop_index(op.f('ix_assessment_rounds_session_type_status'), table_name='assessment_rounds')
    op.drop_index(op.f('one_active_round_per_session'), table_name='assessment_rounds', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_assessment_rounds_id'), 'assessment_rounds', ['id'], unique=False)
    op.alter_column('assessment_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessment_sessions', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('one_active_session_per_user'), table_name='assessment_sessions', postgresql_where="((status)::text = 'in_progress'::text)")
    op.create_index(op.f('ix_assessment_sessions_id'), 'assessment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    op.drop_index(op.f('idx_coding_submission_round'), table_name='coding_submissions')
    op.drop_index(op.f('idx_judge0_token'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_round_problem'), table_name='coding_submissions')
    op.create_index(op.f('ix_coding_submissions_id'), 'coding_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_judge0_token'), 'coding_submissions', ['judge0_token'], unique=False)
    op.create_index(op.f('ix_coding_submissions_round_id'), 'coding_submissions', ['round_id'], unique=False)
    op.alter_column('coding_test_cases', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_coding_test_cases_id'), 'coding_test_cases', ['id'], unique=False)
    op.drop_constraint(op.f('dynamic_interviewers_slug_key'), 'dynamic_interviewers', type_='unique')
    op.add_column('interview_sessions', sa.Column('round_id', sa.Integer(), nullable=True))
    op.add_column('interview_sessions', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('interview_sessions', sa.Column('completion_reason', sa.String(length=30), nullable=True))
    op.add_column('interview_sessions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('interview_sessions', sa.Column('interviewer_id', sa.String(length=50), nullable=True))
    op.add_column('interview_sessions', sa.Column('retell_call_id', sa.String(length=100), nullable=True))
    op.add_column('interview_sessions', sa.Column('retell_agent_id', sa.String(length=100), nullable=True))
    op.add_column('interview_sessions', sa.Column('extraction_confidence', sa.String(length=10), nullable=True))
    op.add_column('interview_sessions', sa.Column('retrieval_success_rate', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('question_personalization_rate', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('personalization_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_sessions', sa.Column('follow_up_quality_score', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('personalization_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_interview_session'), table_name='interview_sessions')
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_retell_call_id'), 'interview_sessions', ['retell_call_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_round_id'), 'interview_sessions', ['round_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_session_id'), 'interview_sessions', ['session_id'], unique=False)
    op.create_foreign_key(None, 'interview_sessions', 'assessment_rounds', ['round_id'], ['id'], ondelete='CASCADE')
    op.add_column('interview_turns', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('interview_turns', sa.Column('intent', sa.String(length=10), nullable=True))
    op.add_column('interview_turns', sa.Column('is_followup', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('interview_turns', sa.Column('followup_number', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('interview_turns', sa.Column('parent_turn_id', sa.Integer(), nullable=True))
    op.add_column('interview_turns', sa.Column('personalization_source', sa.String(length=200), nullable=True))
    op.add_column('interview_turns', sa.Column('question_grounding_confidence', sa.Float(), nullable=True))
    op.add_column('interview_turns', sa.Column('answer_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_turns', sa.Column('followup_grounding_score', sa.Float(), nullable=True))
    op.add_column('interview_turns', sa.Column('followup_targeted_aspect', sa.String(length=200), nullable=True))
    op.drop_index(op.f('idx_interview_turns_interview'), table_name='interview_turns')
    op.drop_index(op.f('idx_interview_turns_turn'), table_name='interview_turns')
    op.create_index(op.f('ix_interview_turns_id'), 'interview_turns', ['id'], unique=False)
    op.create_index(op.f('ix_interview_turns_interview_id'), 'interview_turns', ['interview_id'], unique=False)
    op.create_foreign_key(None, 'interview_turns', 'interview_turns', ['parent_turn_id'], ['id'])
    op.alter_column('proctoring_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('proctoring_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_proctoring_session'), table_name='proctoring_events')
    op.create_index(op.f('ix_proctoring_events_event_type'), 'proctoring_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_proctoring_events_id'), 'proctoring_events', ['id'], unique=False)
    op.create_index(op.f('ix_proctoring_events_session_id'), 'proctoring_events', ['session_id'], unique=False)
    op.drop_index(op.f('idx_violations_session'), table_name='proctoring_violations')
    op.create_index(op.f('ix_proctoring_violations_id'), 'proctoring_violations', ['id'], unique=False)
    op.create_index(op.f('ix_proctoring_violations_session_id'), 'proctoring_violations', ['session_id'], unique=False)
    op.create_foreign_key(None, 'proctoring_violations', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_rl_attempt_log_id'), 'rl_attempt_log', ['id'], unique=False)
    op.alter_column('rl_sessions', 'q_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('rl_sessions_round_id_step_number_key'), 'rl_sessions', type_='unique')
    op.create_index(op.f('ix_rl_sessions_id'), 'rl_sessions', ['id'], unique=False)
    op.drop_index(op.f('idx_session_problems_round'), table_name='session_problems')
    op.create_index(op.f('ix_session_problems_id'), 'session_problems', ['id'], unique=False)
    op.alter_column('user_resumes', 'resume_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_resumes', 'parsed_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_resumes', 'parsed_projects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_resumes', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_resumes_id'), 'user_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_user_resumes_user_id'), 'user_resumes', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_resumes_user_id'), table_name='user_resumes')
    op.drop_index(op.f('ix_user_resumes_id'), table_name='user_resumes')
    op.alter_column('user_resumes', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_resumes', 'parsed_projects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_resumes', 'parsed_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_resumes', 'resume_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_session_problems_id'), table_name='session_problems')
    op.create_index(op.f('idx_session_problems_round'), 'session_problems', ['round_id'], unique=False)
    op.drop_index(op.f('ix_rl_sessions_id'), table_name='rl_sessions')
    op.create_unique_constraint(op.f('rl_sessions_round_id_step_number_key'), 'rl_sessions', ['round_id', 'step_number'])
    op.alter_column('rl_sessions', 'q_values',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_rl_attempt_log_id'), table_name='rl_attempt_log')
    op.drop_constraint(None, 'proctoring_violations', type_='foreignkey')
    op.drop_index(op.f('ix_proctoring_violations_session_id'), table_name='proctoring_violations')
    op.drop_index(op.f('ix_proctoring_violations_id'), table_name='proctoring_violations')
    op.create_index(op.f('idx_violations_session'), 'proctoring_violations', ['session_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_proctoring_events_session_id'), table_name='proctoring_events')
    op.drop_index(op.f('ix_proctoring_events_id'), table_name='proctoring_events')
    op.drop_index(op.f('ix_proctoring_events_event_type'), table_name='proctoring_events')
    op.create_index(op.f('idx_proctoring_session'), 'proctoring_events', ['session_id'], unique=False)
    op.alter_column('proctoring_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proctoring_events', 'event_metadata',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'interview_turns', type_='foreignkey')
    op.drop_index(op.f('ix_interview_turns_interview_id'), table_name='interview_turns')
    op.drop_index(op.f('ix_interview_turns_id'), table_name='interview_turns')
    op.create_index(op.f('idx_interview_turns_turn'), 'interview_turns', ['interview_id', 'turn_number'], unique=False)
    op.create_index(op.f('idx_interview_turns_interview'), 'interview_turns', ['interview_id'], unique=False)
    op.drop_column('interview_turns', 'followup_targeted_aspect')
    op.drop_column('interview_turns', 'followup_grounding_score')
    op.drop_column('interview_turns', 'answer_classification')
    op.drop_column('interview_turns', 'question_grounding_confidence')
    op.drop_column('interview_turns', 'personalization_source')
    op.drop_column('interview_turns', 'parent_turn_id')
    op.drop_column('interview_turns', 'followup_number')
    op.drop_column('interview_turns', 'is_followup')
    op.drop_column('interview_turns', 'intent')
    op.drop_column('interview_turns', 'final_score')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_sessions_session_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_round_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_retell_call_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.create_index(op.f('idx_interview_session'), 'interview_sessions', ['session_id'], unique=False)
    op.drop_column('interview_sessions', 'personalization_warnings')
    op.drop_column('interview_sessions', 'follow_up_quality_score')
    op.drop_column('interview_sessions', 'personalization_metadata')
    op.drop_column('interview_sessions', 'question_personalization_rate')
    op.drop_column('interview_sessions', 'retrieval_success_rate')
    op.drop_column('interview_sessions', 'extraction_confidence')
    op.drop_column('interview_sessions', 'retell_agent_id')
    op.drop_column('interview_sessions', 'retell_call_id')
    op.drop_column('interview_sessions', 'interviewer_id')
    op.drop_column('interview_sessions', 'completed_at')
    op.drop_column('interview_sessions', 'completion_reason')
    op.drop_column('interview_sessions', 'status')
    op.drop_column('interview_sessions', 'round_id')
    op.create_unique_constraint(op.f('dynamic_interviewers_slug_key'), 'dynamic_interviewers', ['slug'])
    op.drop_index(op.f('ix_coding_test_cases_id'), table_name='coding_test_cases')
    op.alter_column('coding_test_cases', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_coding_submissions_round_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_judge0_token'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_id'), table_name='coding_submissions')
    op.create_index(op.f('ix_coding_submissions_round_problem'), 'coding_submissions', ['round_id', 'problem_id'], unique=False)
    op.create_index(op.f('idx_judge0_token'), 'coding_submissions', ['judge0_token'], unique=False)
    op.create_index(op.f('idx_coding_submission_round'), 'coding_submissions', ['round_id'], unique=False)
    op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
    op.drop_index(op.f('ix_assessment_sessions_id'), table_name='assessment_sessions')
    op.create_index(op.f('one_active_session_per_user'), 'assessment_sessions', ['user_id'], unique=True, postgresql_where="((status)::text = 'in_progress'::text)")
    op.alter_column('assessment_sessions', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('assessment_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_assessment_rounds_id'), table_name='assessment_rounds')
    op.create_index(op.f('one_active_round_per_session'), 'assessment_rounds', ['session_id'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_assessment_rounds_session_type_status'), 'assessment_rounds', ['session_id', 'round_type', 'status'], unique=False)
    op.create_index(op.f('idx_round_session'), 'assessment_rounds', ['session_id'], unique=False)
    op.alter_column('assessment_rounds', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('assessment_rounds', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_aptitude_topics_id'), table_name='aptitude_topics')
    op.drop_index(op.f('ix_aptitude_questions_id'), table_name='aptitude_questions')
    op.drop_index(op.f('ix_aptitude_questions_difficulty'), table_name='aptitude_questions')
    op.create_index(op.f('idx_aptitude_difficulty'), 'aptitude_questions', ['difficulty'], unique=False)
    op.alter_column('aptitude_questions', 'correct_option',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_index(op.f('ix_aptitude_attempts_id'), table_name='aptitude_attempts')
    op.create_unique_constraint(op.f('aptitude_attempts_round_id_attempt_number_key'), 'aptitude_attempts', ['round_id', 'attempt_number'])
    op.alter_column('aptitude_attempts', 'selected_option',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_approved_question_pools_session_id'), table_name='approved_question_pools')
    op.drop_index(op.f('ix_approved_question_pools_id'), table_name='approved_question_pools')
    op.drop_index(op.f('ix_approved_question_pools_admin_approved'), table_name='approved_question_pools')
    op.create_index(op.f('idx_approved_pool_session'), 'approved_question_pools', ['session_id'], unique=False)
    op.create_index(op.f('idx_approved_pool_approved'), 'approved_question_pools', ['admin_approved'], unique=False)
    op.create_table_comment(
        'advanced_proctoring_events',
        'Advanced proctoring events with AI-based detection capabilities including computer vision, audio analysis, and confidence scoring',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_advanced_proctoring_events_session_id'), table_name='advanced_proctoring_events')
    op.drop_index(op.f('ix_advanced_proctoring_events_id'), table_name='advanced_proctoring_events')
    op.drop_index(op.f('ix_advanced_proctoring_events_event_type'), table_name='advanced_proctoring_events')
    op.drop_index(op.f('ix_advanced_proctoring_events_created_at'), table_name='advanced_proctoring_events')
    op.create_index(op.f('ix_adv_proctoring_events_session_type'), 'advanced_proctoring_events', ['session_id', 'event_type'], unique=False)
    op.create_index(op.f('idx_proctoring_severity'), 'advanced_proctoring_events', ['severity'], unique=False)
    op.create_index(op.f('idx_proctoring_round'), 'advanced_proctoring_events', ['round_type'], unique=False)
    op.create_index(op.f('idx_proctoring_metadata'), 'advanced_proctoring_events', ['event_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_proctoring_event_type'), 'advanced_proctoring_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_proctoring_dedup'), 'advanced_proctoring_events', ['session_id', 'event_type', sa.literal_column("date_trunc('second'::text, created_at)")], unique=True)
    op.create_index(op.f('idx_proctoring_created_at'), 'advanced_proctoring_events', ['created_at'], unique=False)
    op.alter_column('advanced_proctoring_events', 'event_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Detailed detection metadata including bounding boxes, landmarks, audio features, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('advanced_proctoring_events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='AI model confidence score (0.0-1.0) for detection',
               existing_nullable=True)
    op.alter_column('advanced_proctoring_events', 'round_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Assessment round type: APTITUDE, CODING, or INTERVIEW',
               existing_nullable=True)
    op.alter_column('advanced_proctoring_events', 'severity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               comment='Severity level: INFO, WARNING, or CRITICAL',
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))
    op.alter_column('advanced_proctoring_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of proctoring event (e.g., MULTIPLE_PERSON_DETECTED, FACE_NOT_VISIBLE, etc.)',
               existing_nullable=False)
    op.alter_column('advanced_proctoring_events', 'session_id',
               existing_type=sa.INTEGER(),
               comment='Reference to assessment session',
               existing_nullable=False)
    op.create_table('resume_processing_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], name=op.f('resume_processing_jobs_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resume_processing_jobs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_processing_jobs_pkey'))
    )
    op.create_index(op.f('ix_resume_processing_jobs_user_id'), 'resume_processing_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_processing_jobs_status'), 'resume_processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_resume_processing_jobs_session_id'), 'resume_processing_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_resume_processing_jobs_created_at'), 'resume_processing_jobs', ['created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('idx_refresh_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###
