-- ============================================
-- AI Placement Platform Database Schema - COMPLETE CONSOLIDATED VERSION
-- PostgreSQL
-- Generated by consolidating: schema.sql, missing_tables.sql, advanced_proctoring_schema.sql, fix_interview_sessions.sql
-- ============================================


-- ============================================
-- USERS
-- ============================================
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'student',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (role IN ('student', 'faculty', 'tpo', 'admin'))
);

CREATE INDEX idx_users_email ON users(email);


-- ============================================
-- USER PROFILES
-- ============================================
CREATE TABLE student_profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    roll_number VARCHAR(50),
    department VARCHAR(100) NOT NULL,
    cgpa FLOAT NOT NULL,
    graduation_year INTEGER NOT NULL,
    backlogs_count INTEGER NOT NULL,
    institution VARCHAR(200) NOT NULL,
    target_role VARCHAR(100),
    skills_json JSONB NOT NULL,
    phone_number VARCHAR(20),
    mobile_no VARCHAR(50),
    full_name VARCHAR(150),
    college_email_id VARCHAR(150),
    gender VARCHAR(50),
    date_of_birth VARCHAR(50),
    nationality VARCHAR(100),
    tenth_marks FLOAT,
    twelfth_marks FLOAT,
    bio TEXT,
    portfolio_data JSONB DEFAULT '{}' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE faculty_profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    department VARCHAR(100) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    institution VARCHAR(200) NOT NULL,
    employee_id VARCHAR(50),
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE tpo_profiles (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    institution VARCHAR(200) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    contact_email VARCHAR(150),
    contact_phone VARCHAR(20),
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- ============================================
-- REFRESH TOKENS
-- ============================================
CREATE TABLE refresh_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_hash ON refresh_tokens(token_hash);


-- ============================================
-- USER RESUMES
-- ============================================
CREATE TABLE user_resumes (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    cv_name VARCHAR(200) NOT NULL,
    cv_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size INTEGER NOT NULL,
    resume_text TEXT,
    parsed_skills JSONB NOT NULL DEFAULT '[]',
    parsed_projects JSONB NOT NULL DEFAULT '{}',
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_resumes_user_id ON user_resumes(user_id);


-- ============================================
-- ASSESSMENT POLICIES & CONTEXTS
-- ============================================
CREATE TABLE assessment_policies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    session_duration_minutes INTEGER NOT NULL,
    round_duration_minutes INTEGER NOT NULL,
    max_attempts INTEGER,
    resume_allowed BOOLEAN NOT NULL,
    exit_allowed BOOLEAN NOT NULL,
    progression_mode VARCHAR(20) NOT NULL,
    progression_config JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assessment_contexts (
    id SERIAL PRIMARY KEY,
    mode VARCHAR(50) NOT NULL,
    purpose VARCHAR(100),
    created_by_id INTEGER,
    student_id INTEGER,
    company_name VARCHAR(200),
    target_role VARCHAR(100),
    jd_text TEXT,
    availability_start TIMESTAMP,
    availability_end TIMESTAMP,
    policy_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (policy_id) REFERENCES assessment_policies(id)
);

CREATE INDEX idx_assessment_contexts_student_id ON assessment_contexts(student_id);
CREATE INDEX idx_assessment_contexts_policy_id ON assessment_contexts(policy_id);


-- ============================================
-- ASSESSMENT SESSIONS
-- ============================================
CREATE TABLE assessment_sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    context_id INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'not_started'
        CHECK (status IN ('not_started','in_progress','completed','terminated','expired')),
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    completed_at TIMESTAMP,
    total_score FLOAT DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (context_id) REFERENCES assessment_contexts(id)
);

CREATE UNIQUE INDEX one_active_session_per_user
ON assessment_sessions(user_id)
WHERE status='in_progress';

CREATE INDEX idx_assessment_sessions_context_id ON assessment_sessions(context_id);


-- ============================================
-- ASSESSMENT ROUNDS
-- ============================================
CREATE TABLE assessment_rounds (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL,
    round_type VARCHAR(20) NOT NULL
        CHECK (round_type IN ('aptitude','coding','interview')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','active','completed','terminated','expired')),
    score FLOAT DEFAULT 0,
    max_questions INTEGER NOT NULL DEFAULT 20,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (session_id)
        REFERENCES assessment_sessions(id) ON DELETE CASCADE
);

CREATE INDEX idx_round_session ON assessment_rounds(session_id);


-- ============================================
-- APTITUDE TOPICS
-- ============================================
CREATE TABLE aptitude_topics (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);


-- ============================================
-- APTITUDE QUESTIONS
-- ============================================
CREATE TABLE aptitude_questions (
    id SERIAL PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option CHAR(1) NOT NULL
        CHECK (correct_option IN ('A','B','C','D')),
    difficulty VARCHAR(10) NOT NULL
        CHECK (difficulty IN ('easy','medium','hard')),
    topic_id INTEGER,
    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topic_id) REFERENCES aptitude_topics(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_aptitude_difficulty ON aptitude_questions(difficulty);
CREATE INDEX idx_aptitude_topic ON aptitude_questions(topic_id);


-- ============================================
-- ADMIN QUESTION FEEDBACK
-- ============================================
CREATE TABLE admin_question_feedback (
    id SERIAL PRIMARY KEY,
    question_id INTEGER NOT NULL,
    admin_id INTEGER,
    action VARCHAR(20) NOT NULL
        CHECK (action IN ('approve','reject','review')),
    suggestion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (question_id)
        REFERENCES aptitude_questions(id) ON DELETE CASCADE,
    FOREIGN KEY (admin_id)
        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_admin_qf_question_id ON admin_question_feedback(question_id);
CREATE INDEX idx_admin_qf_admin_id ON admin_question_feedback(admin_id);


-- ============================================
-- APTITUDE ATTEMPTS
-- ============================================
CREATE TABLE aptitude_attempts (
    id SERIAL PRIMARY KEY,
    round_id INTEGER NOT NULL,
    question_id INTEGER NOT NULL,
    attempt_number INTEGER NOT NULL,
    selected_option CHAR(1),
    is_correct BOOLEAN,
    response_time FLOAT,
    difficulty VARCHAR(10),
    reward FLOAT,
    attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (round_id)
        REFERENCES assessment_rounds(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id)
        REFERENCES aptitude_questions(id),
    UNIQUE (round_id, attempt_number)
);

CREATE INDEX idx_aptitude_attempts_round ON aptitude_attempts(round_id);
CREATE INDEX idx_aptitude_attempts_question ON aptitude_attempts(question_id);


-- ============================================
-- RL SESSIONS (Reinforcement Learning for Adaptive Difficulty)
-- ============================================
CREATE TABLE rl_sessions (
    id SERIAL PRIMARY KEY,
    round_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    prev_difficulty VARCHAR(10)
        CHECK (prev_difficulty IN ('easy','medium','hard')),
    action_taken VARCHAR(10) NOT NULL
        CHECK (action_taken IN ('easy','medium','hard')),
    reward_received FLOAT,
    accuracy_so_far FLOAT,
    avg_response_time FLOAT,
    q_values JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (round_id)
        REFERENCES assessment_rounds(id) ON DELETE CASCADE,
    UNIQUE (round_id, step_number)
);

CREATE INDEX idx_rl_sessions_round ON rl_sessions(round_id);


-- ============================================
-- RL Q-TABLE (Global Q-Table for RL)
-- ============================================
CREATE TABLE rl_q_table (
    user_id INTEGER NOT NULL,
    state TEXT NOT NULL,
    action TEXT NOT NULL,
    q_value FLOAT DEFAULT 0.1,
    visit_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, state, action),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_rl_q_table_user ON rl_q_table(user_id);


-- ============================================
-- RL ATTEMPT LOG (Detailed RL Training Log)
-- ============================================
CREATE TABLE rl_attempt_log (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    session_id INTEGER,
    question_id INTEGER,
    difficulty TEXT,
    state_before TEXT,
    action_taken TEXT,
    reward FLOAT,
    state_after TEXT,
    response_time FLOAT,
    is_correct BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (session_id) REFERENCES assessment_sessions(id),
    FOREIGN KEY (question_id) REFERENCES aptitude_questions(id)
);

CREATE INDEX idx_rl_attempt_log_user ON rl_attempt_log(user_id);
CREATE INDEX idx_rl_attempt_log_session ON rl_attempt_log(session_id);


-- ============================================
-- CODING PROBLEMS
-- ============================================
CREATE TABLE coding_problems (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    difficulty VARCHAR(10)
        CHECK (difficulty IN ('easy','medium','hard')),
    tags TEXT[],
    input_format TEXT,
    output_format TEXT,
    constraints TEXT,
    created_by INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_coding_problems_difficulty ON coding_problems(difficulty);
CREATE INDEX idx_coding_problems_created_by ON coding_problems(created_by);


-- ============================================
-- CODING TEST CASES
-- ============================================
CREATE TABLE coding_test_cases (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER NOT NULL,
    input_data TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_hidden BOOLEAN DEFAULT TRUE,
    case_order INTEGER NOT NULL DEFAULT 0,
    explanation TEXT,
    FOREIGN KEY (problem_id)
        REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE INDEX idx_coding_test_cases_problem ON coding_test_cases(problem_id);


-- ============================================
-- SESSION PROBLEMS (assigned coding problems per round)
-- ============================================
CREATE TABLE session_problems (
    id SERIAL PRIMARY KEY,
    round_id INTEGER NOT NULL,
    problem_id INTEGER NOT NULL,
    problem_order INTEGER NOT NULL DEFAULT 0,
    marked_for_review BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (round_id) REFERENCES assessment_rounds(id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id) REFERENCES coding_problems(id) ON DELETE CASCADE
);

CREATE INDEX idx_session_problems_round ON session_problems(round_id);
CREATE INDEX idx_session_problems_problem ON session_problems(problem_id);


-- ============================================
-- CODING SUBMISSIONS
-- ============================================
CREATE TABLE coding_submissions (
    id SERIAL PRIMARY KEY,
    round_id INTEGER NOT NULL,
    problem_id INTEGER NOT NULL,
    code TEXT NOT NULL,
    language VARCHAR(50),
    judge0_token VARCHAR(100),
    status VARCHAR(30)
        CHECK (status IN (
            'running',
            'accepted',
            'wrong_answer',
            'runtime_error',
            'time_limit_exceeded',
            'compilation_error'
        )),
    score FLOAT,
    execution_time FLOAT,
    memory_used INTEGER,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (round_id)
        REFERENCES assessment_rounds(id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id)
        REFERENCES coding_problems(id)
);

CREATE INDEX idx_coding_submission_round ON coding_submissions(round_id);
CREATE INDEX idx_coding_submission_problem ON coding_submissions(problem_id);
CREATE INDEX idx_judge0_token ON coding_submissions(judge0_token);


-- ============================================
-- APPROVED QUESTION POOLS
-- ============================================
CREATE TABLE approved_question_pools (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL,
    extracted_skills JSONB NOT NULL DEFAULT '[]',
    extracted_projects JSONB NOT NULL DEFAULT '{}',
    question_pool JSONB NOT NULL,
    admin_approved BOOLEAN NOT NULL DEFAULT false,
    approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMP,
    detected_role VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id)
        REFERENCES assessment_sessions(id) ON DELETE CASCADE
);

CREATE INDEX ix_approved_question_pools_session_id ON approved_question_pools(session_id);
CREATE INDEX ix_approved_question_pools_admin_approved ON approved_question_pools(admin_approved);


-- ============================================
-- PROCTORING EVENTS (Basic)
-- ============================================
CREATE TABLE proctoring_events (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (session_id)
        REFERENCES assessment_sessions(id) ON DELETE CASCADE
);

CREATE INDEX idx_proctoring_session ON proctoring_events(session_id);
CREATE INDEX idx_proctoring_event_type ON proctoring_events(event_type);
CREATE INDEX idx_proctoring_created_at ON proctoring_events(created_at);


-- ============================================
-- ADVANCED PROCTORING EVENTS (AI-Based)
-- ============================================
CREATE TABLE advanced_proctoring_events (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    severity VARCHAR(10) NOT NULL DEFAULT 'INFO',
    round_type VARCHAR(20) CHECK (round_type IN ('APTITUDE', 'CODING', 'INTERVIEW')),
    confidence FLOAT CHECK (confidence >= 0.0 AND confidence <= 1.0),
    event_metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (session_id) 
        REFERENCES assessment_sessions(id) 
        ON DELETE CASCADE,
    
    CONSTRAINT chk_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

CREATE INDEX idx_adv_proctoring_session ON advanced_proctoring_events(session_id);
CREATE INDEX idx_adv_proctoring_event_type ON advanced_proctoring_events(event_type);
CREATE INDEX idx_adv_proctoring_severity ON advanced_proctoring_events(severity);
CREATE INDEX idx_adv_proctoring_round ON advanced_proctoring_events(round_type);
CREATE INDEX idx_adv_proctoring_created_at ON advanced_proctoring_events(created_at);
CREATE INDEX idx_adv_proctoring_metadata ON advanced_proctoring_events USING GIN(event_metadata);

-- Deduplication index (prevents duplicate burst events within same second)
CREATE UNIQUE INDEX idx_adv_proctoring_dedup
ON advanced_proctoring_events (session_id, event_type, date_trunc('second', created_at));

COMMENT ON TABLE advanced_proctoring_events IS 'Advanced proctoring events with AI-based detection capabilities including computer vision, audio analysis, and confidence scoring';
COMMENT ON COLUMN advanced_proctoring_events.session_id IS 'Reference to assessment session';
COMMENT ON COLUMN advanced_proctoring_events.event_type IS 'Type of proctoring event (e.g., MULTIPLE_PERSON_DETECTED, FACE_NOT_VISIBLE, etc.)';
COMMENT ON COLUMN advanced_proctoring_events.severity IS 'Severity level: INFO, WARNING, or CRITICAL';
COMMENT ON COLUMN advanced_proctoring_events.round_type IS 'Assessment round type: APTITUDE, CODING, or INTERVIEW';
COMMENT ON COLUMN advanced_proctoring_events.confidence IS 'AI model confidence score (0.0-1.0) for detection';
COMMENT ON COLUMN advanced_proctoring_events.event_metadata IS 'Detailed detection metadata including bounding boxes, landmarks, audio features, etc.';


-- ============================================
-- INTERVIEW SESSIONS
-- ============================================
CREATE TABLE interview_sessions (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES assessment_sessions(id) ON DELETE CASCADE,
    round_id INTEGER REFERENCES assessment_rounds(id) ON DELETE CASCADE,
    phase VARCHAR(20) NOT NULL DEFAULT 'HR',
    current_turn INTEGER NOT NULL DEFAULT 0,
    total_turns INTEGER NOT NULL DEFAULT 10,
    rl_state JSONB NOT NULL DEFAULT '{}',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    completion_reason VARCHAR(30),
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX ix_interview_sessions_session_id ON interview_sessions(session_id);
CREATE INDEX ix_interview_sessions_round_id ON interview_sessions(round_id);


-- ============================================
-- INTERVIEW TURNS
-- ============================================
CREATE TABLE interview_turns (
    id SERIAL PRIMARY KEY,
    interview_id INTEGER NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
    turn_number INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    question_difficulty VARCHAR(10),
    candidate_response TEXT,
    response_time_sec FLOAT,
    content_score FLOAT,
    final_score FLOAT,
    intent VARCHAR(10),
    behavioral_snapshot JSONB NOT NULL DEFAULT '{}',
    rl_reward FLOAT,
    is_followup BOOLEAN NOT NULL DEFAULT false,
    followup_number INTEGER NOT NULL DEFAULT 0,
    parent_turn_id INTEGER REFERENCES interview_turns(id),
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX ix_interview_turns_interview_id ON interview_turns(interview_id);


-- ============================================
-- PROCTORING VIOLATIONS (Interview-specific)
-- ============================================
CREATE TABLE proctoring_violations (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    confidence_score FLOAT,
    face_count INTEGER,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX ix_proctoring_violations_session_id ON proctoring_violations(session_id);


-- ============================================
-- MATERIALIZED VIEW: ROUND ANALYTICS
-- ============================================
CREATE MATERIALIZED VIEW round_analytics AS

SELECT
    r.id AS round_id,
    r.round_type,
    COUNT(aa.id) AS total_questions,
    SUM(CASE WHEN aa.is_correct THEN 1 ELSE 0 END) AS correct_answers,
    AVG(aa.response_time) AS avg_response_time,
    NULL::FLOAT AS coding_score
FROM assessment_rounds r
LEFT JOIN aptitude_attempts aa ON aa.round_id = r.id
WHERE r.round_type = 'aptitude'
GROUP BY r.id, r.round_type

UNION ALL

SELECT
    r.id,
    r.round_type,
    COUNT(cs.id),
    NULL,
    NULL,
    AVG(cs.score)
FROM assessment_rounds r
LEFT JOIN coding_submissions cs ON cs.round_id = r.id
WHERE r.round_type = 'coding'
GROUP BY r.id, r.round_type;

CREATE UNIQUE INDEX idx_round_analytics_round_id
ON round_analytics(round_id);


-- ============================================
-- VIEW: HIGH RISK SESSIONS (Advanced Proctoring)
-- ============================================
CREATE OR REPLACE VIEW high_risk_sessions AS
SELECT 
    session_id,
    COUNT(*) as event_count,
    calculate_session_risk_score(session_id) as avg_risk_score,
    MAX(CAST(event_metadata->>'risk_score' AS FLOAT)) as max_risk_score,
    COUNT(*) FILTER (WHERE severity = 'CRITICAL') as critical_violation_count,
    COUNT(*) FILTER (WHERE severity = 'WARNING') as warning_violation_count,
    COUNT(*) FILTER (WHERE event_type = 'MULTIPLE_PERSON_DETECTED') as multiple_person_count,
    COUNT(*) FILTER (WHERE event_type = 'FACE_NOT_VISIBLE') as face_not_visible_count,
    COUNT(*) FILTER (WHERE event_type = 'VOICE_ACTIVITY_DETECTED') as voice_activity_count,
    COUNT(*) FILTER (WHERE event_type IN ('TAB_SWITCH', 'FULLSCREEN_EXIT', 'PAGE_RELOAD')) as browser_violation_count,
    MAX(created_at) as last_activity,
    MIN(created_at) as first_activity
FROM advanced_proctoring_events
GROUP BY session_id
HAVING calculate_session_risk_score(session_id) > 0.5
ORDER BY avg_risk_score DESC;

COMMENT ON VIEW high_risk_sessions IS 'View of sessions with elevated proctoring risk scores for admin dashboard';


-- ============================================
-- FUNCTION: CALCULATE SESSION RISK SCORE
-- ============================================
CREATE OR REPLACE FUNCTION calculate_session_risk_score(p_session_id INTEGER)
RETURNS FLOAT AS $$
DECLARE
    total_weighted_score FLOAT;
    event_count INTEGER;
    final_score FLOAT;
BEGIN
    SELECT 
        SUM(CASE 
            WHEN event_type = 'MULTIPLE_PERSON_DETECTED' THEN 0.9 * confidence
            WHEN event_type = 'CAMERA_PERMISSION_DENIED' THEN 0.9 * confidence
            WHEN event_type = 'PAGE_RELOAD' THEN 0.8 * confidence
            WHEN event_type = 'FACE_NOT_VISIBLE' THEN 0.7 * confidence
            WHEN event_type = 'VOICE_ACTIVITY_DETECTED' THEN 0.6 * confidence
            WHEN event_type = 'FULLSCREEN_EXIT' THEN 0.4 * confidence
            WHEN event_type = 'HEAD_TURN_DETECTED' THEN 0.4 * confidence
            WHEN event_type = 'MOUTH_MOVEMENT_DETECTED' THEN 0.3 * confidence
            WHEN event_type = 'TAB_SWITCH' THEN 0.3 * confidence
            WHEN event_type = 'LOOKING_AWAY' THEN 0.3 * confidence
            WHEN event_type = 'IDLE_ACTIVITY' THEN 0.2 * confidence
            ELSE 0.1 * confidence
        END)
    INTO total_weighted_score
    FROM advanced_proctoring_events
    WHERE session_id = p_session_id;
    
    SELECT COUNT(*)
    INTO event_count
    FROM advanced_proctoring_events
    WHERE session_id = p_session_id;
    
    -- Calculate average and cap at 1.0
    final_score := CASE 
        WHEN event_count > 0 THEN LEAST(total_weighted_score / event_count, 1.0)
        ELSE 0.0
    END;
    
    RETURN COALESCE(final_score, 0.0);
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION calculate_session_risk_score(INTEGER) IS 'Calculate comprehensive risk score for a session based on all proctoring events, capped at 1.0';


-- ============================================
-- TRIGGER: UPDATE EVENT RISK SCORE
-- ============================================
CREATE OR REPLACE FUNCTION update_event_risk_score()
RETURNS TRIGGER AS $$
DECLARE
    raw_score FLOAT;
BEGIN
    -- Calculate raw risk score based on event type
    raw_score := CASE NEW.event_type
        WHEN 'MULTIPLE_PERSON_DETECTED'  THEN 0.9
        WHEN 'CAMERA_PERMISSION_DENIED'  THEN 0.9
        WHEN 'PAGE_RELOAD'               THEN 0.8
        WHEN 'FACE_NOT_VISIBLE'          THEN 0.7
        WHEN 'VOICE_ACTIVITY_DETECTED'   THEN 0.6
        WHEN 'FULLSCREEN_EXIT'           THEN 0.4
        WHEN 'HEAD_TURN_DETECTED'        THEN 0.4
        WHEN 'MOUTH_MOVEMENT_DETECTED'   THEN 0.3
        WHEN 'TAB_SWITCH'               THEN 0.3
        WHEN 'LOOKING_AWAY'             THEN 0.3
        WHEN 'IDLE_ACTIVITY'            THEN 0.2
        ELSE 0.1
    END * NEW.confidence;

    -- Set severity based on event type
    NEW.severity := CASE NEW.event_type
        WHEN 'MULTIPLE_PERSON_DETECTED' THEN 'CRITICAL'
        WHEN 'FACE_NOT_VISIBLE'         THEN 'CRITICAL'
        WHEN 'CAMERA_PERMISSION_DENIED' THEN 'CRITICAL'
        WHEN 'PAGE_RELOAD'               THEN 'CRITICAL'
        WHEN 'TAB_SWITCH'               THEN 'WARNING'
        WHEN 'FULLSCREEN_EXIT'          THEN 'WARNING'
        WHEN 'HEAD_TURN_DETECTED'       THEN 'WARNING'
        WHEN 'VOICE_ACTIVITY_DETECTED'  THEN 'WARNING'
        WHEN 'MOUTH_MOVEMENT_DETECTED'   THEN 'WARNING'
        ELSE 'INFO'
    END;

    -- Set round_type based on session (would need to join with assessment_sessions)
    -- For now, default to APTITUDE - this should be updated in application layer
    NEW.round_type := 'APTITUDE';

    -- Safe null guard before jsonb_set
    NEW.event_metadata := COALESCE(NEW.event_metadata, '{}');
    NEW.event_metadata := jsonb_set(
        NEW.event_metadata, 
        '{risk_score}', 
        to_jsonb(LEAST(raw_score, 1.0))
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_event_risk_score
    BEFORE INSERT OR UPDATE ON advanced_proctoring_events
    FOR EACH ROW
    EXECUTE FUNCTION update_event_risk_score();


-- ============================================
-- FUNCTION: CLEANUP OLD PROCTORING EVENTS
-- ============================================
CREATE OR REPLACE FUNCTION cleanup_old_proctoring_events(days_to_keep INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER := 0;
    batch_count INTEGER := 0;
    total_deleted INTEGER := 0;
BEGIN
    LOOP
        -- Delete in batches of 10,000 to avoid table locks
        DELETE FROM advanced_proctoring_events 
        WHERE id IN (
            SELECT id FROM advanced_proctoring_events
            WHERE created_at < CURRENT_DATE - INTERVAL '1 day' * days_to_keep
            LIMIT 10000
        );
        
        GET DIAGNOSTICS batch_count = ROW_COUNT;
        total_deleted := total_deleted + batch_count;
        
        -- Exit when no more rows to delete
        EXIT WHEN batch_count = 0;
        
        -- Commit each batch to avoid long transactions
        COMMIT;
        
        -- Optional: Add small delay to reduce load
        PERFORM pg_sleep(0.1);
    END LOOP;
    
    RETURN total_deleted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_old_proctoring_events(INTEGER) IS 'Clean up proctoring events older than specified number of days in batches to avoid table locks';